### PR TITLE
Upgrade to Poodinis 8.1.0 (release version)

### PR DESCRIPTION
**Pull request by mbierlee**

### CODE REVIEW

**Comment by Heromyth** [comment]
Thanks. The tests passed.

**Comment by Heromyth** [comment]
It's so sad. The linking seems ok. However, some modules can't be resolved.
Here is an example: https://github.com/huntlabs/hunt-examples/tree/master/website-basic.

- Change `hunt-framework` to `==3.4.6.rc.2` in `dub.json`.  
- Run `dub run --compiler=dmd -a=x86_64 -b=debug`.

- The errors:
```sh
2021-08-24 09:56:25 (18848) [info] registerProviders - Registering all the service providers (14)... - ../../hunt-framework/source/hunt/framework/application/Application.d:386
poodinis.container.ResolveException@/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d(40): Exception while resolving type hunt.http.server.HttpServerOptions.HttpServerOptions: Type not registered.
----------------
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:363 shared hunt.http.server.HttpServerOptions.HttpServerOptions poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServerOptions.HttpServerOptions, hunt.http.server.HttpServerOptions.HttpServerOptions).resolve(poodinis.container.ResolveOption) [0x564b8a02d805]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:304 shared hunt.http.server.HttpServerOptions.HttpServerOptions poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServerOptions.HttpServerOptions).resolve(poodinis.container.ResolveOption) [0x564b8a02d6a2]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/factory.d:215 Object poodinis.factory.ConstructorInjectingInstanceFactory!(hunt.http.server.HttpServer.HttpServer).ConstructorInjectingInstanceFactory.createInstance() [0x564b89faef67]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/factory.d:96 Object poodinis.factory.InstanceFactory.getInstance() [0x564b8aebae4f]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/registration.d:81 Object poodinis.registration.Registration.getInstance(poodinis.registration.InstantiationContext) [0x564b8aebb25c]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/autowire.d:354 Object poodinis.autowire.AutowiredRegistration!(hunt.http.server.HttpServer.HttpServer).AutowiredRegistration.getInstance(poodinis.registration.InstantiationContext) [0x564b89faf13c]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:394 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolveAutowiredInstance!(hunt.http.server.HttpServer.HttpServer).resolveAutowiredInstance(poodinis.registration.Registration) [0x564b89ed2383]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:371 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServer.HttpServer, hunt.http.server.HttpServer.HttpServer).resolve(poodinis.container.ResolveOption) [0x564b89ed2171]
/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:304 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServer.HttpServer).resolve(poodinis.container.ResolveOption) [0x564b89ed1ff2]
../../hunt-framework/source/hunt/framework/application/Application.d:310 void hunt.framework.application.Application.Application.bootstrap() [0x564b89f86034]
../../hunt-framework/source/hunt/framework/application/Application.d:278 void hunt.framework.application.Application.Application.run(immutable(char)[][]) [0x564b89f85dbc]
source/bootstrap.d:122 _Dmain [0x564b89ee51ce]
```

**Comment by mbierlee** [comment]
> It's so sad. The linking seems ok. However, some modules can't be resolved.
> Here is an example: https://github.com/huntlabs/hunt-examples/tree/master/website-basic.
> 
> * Change `hunt-framework` to `==3.4.6.rc.2` in `dub.json`.
> * Run `dub run --compiler=dmd -a=x86_64 -b=debug`.
> * The errors:
> 
> ```shell
> 2021-08-24 09:56:25 (18848) [info] registerProviders - Registering all the service providers (14)... - ../../hunt-framework/source/hunt/framework/application/Application.d:386
> poodinis.container.ResolveException@/home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d(40): Exception while resolving type hunt.http.server.HttpServerOptions.HttpServerOptions: Type not registered.
> ----------------
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:363 shared hunt.http.server.HttpServerOptions.HttpServerOptions poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServerOptions.HttpServerOptions, hunt.http.server.HttpServerOptions.HttpServerOptions).resolve(poodinis.container.ResolveOption) [0x564b8a02d805]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:304 shared hunt.http.server.HttpServerOptions.HttpServerOptions poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServerOptions.HttpServerOptions).resolve(poodinis.container.ResolveOption) [0x564b8a02d6a2]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/factory.d:215 Object poodinis.factory.ConstructorInjectingInstanceFactory!(hunt.http.server.HttpServer.HttpServer).ConstructorInjectingInstanceFactory.createInstance() [0x564b89faef67]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/factory.d:96 Object poodinis.factory.InstanceFactory.getInstance() [0x564b8aebae4f]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/registration.d:81 Object poodinis.registration.Registration.getInstance(poodinis.registration.InstantiationContext) [0x564b8aebb25c]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/autowire.d:354 Object poodinis.autowire.AutowiredRegistration!(hunt.http.server.HttpServer.HttpServer).AutowiredRegistration.getInstance(poodinis.registration.InstantiationContext) [0x564b89faf13c]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:394 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolveAutowiredInstance!(hunt.http.server.HttpServer.HttpServer).resolveAutowiredInstance(poodinis.registration.Registration) [0x564b89ed2383]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:371 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServer.HttpServer, hunt.http.server.HttpServer.HttpServer).resolve(poodinis.container.ResolveOption) [0x564b89ed2171]
> /home/zhangxueping/.dub/packages/poodinis-8.1.0/poodinis/source/poodinis/container.d:304 shared hunt.http.server.HttpServer.HttpServer poodinis.container.DependencyContainer.resolve!(hunt.http.server.HttpServer.HttpServer).resolve(poodinis.container.ResolveOption) [0x564b89ed1ff2]
> ../../hunt-framework/source/hunt/framework/application/Application.d:310 void hunt.framework.application.Application.Application.bootstrap() [0x564b89f86034]
> ../../hunt-framework/source/hunt/framework/application/Application.d:278 void hunt.framework.application.Application.Application.run(immutable(char)[][]) [0x564b89f85dbc]
> source/bootstrap.d:122 _Dmain [0x564b89ee51ce]
> ```

@Heromyth: I have found the issue, it is a problem in Poodinis:

```d
container.register!HttpServer.initializedBy(&buildServer).singleInstance();
```

The singleInstance() registration scope tosses the factory method away. I will fix this.

**Comment by mbierlee** [comment]
Above issue is fixed in Poodinis 8.1.1

**Comment by Heromyth** [comment]
That's great! Thanks!

**Pull request merged**
