### PR TITLE
repair:  issue #82.

### PR DESCRIPTION
**Pull request by shove70**

### CODE REVIEW

**Comment by shove70** [comment]
repair issue #82

**Comment by shove70** [comment]
In addition, there is a problem with session storage, whether it is memory or file, the storage content does not distinguish between sessionId, that is, all customer access is the same content access. This should be careless omission of low-level errors

**Review by viile — COMMENTED** [review]
string driver = "memory"
the variable driver default value is already "memory"

**Comment by viile** [comment]
you can see the code in 'source/hunt/http/request.d'  , different requests will get different sessionId

**Comment by shove70** [comment]
If you don't give it any value in the application.conf, you'll know the effect

**Comment by shove70** [comment]
Sorry, I've just pasted it wrong. What I want to say is: you try it in filecache mode, and you'll find that the file generated on the server is not sessionId

**Comment by shove70** [comment]
Request does have sessionId, but there is no distinction in fileStorage

**Comment by viile** [comment]
you can look this https://github.com/huntlabs/hunt/blob/master/examples/website/source/app/controller/index.d
in this code line 42.
request.getSession();  
this code will create session file and cookie;

**Pull request closed without merging**
